Const
  Ver                      = 3.50;
  Finish         : Boolean = False;

  PXEFileName              = 'DATA.PXE';
  FontFile                 = 'DEFAULT.FNT';
  MapFileName              = 'DEFAULT.MAP';
  MousePicsFile            = 'MOUSE.PIC';
  JeepFileName1            = 'JEEP.PIC';
  JeepFileName2            = 'JEEP2.PIC';
  Fire1FileName            = 'FIRE1.PIC';
  Fire2FileName            = 'FIRE2.PIC';
  MasheuFileName           = 'MASHEU.PIC';
  JeepCanonFileName        = 'CANNON.PIC';
  BadCannonFileName        = 'BCANNON.PIC';
  BCannonBaseFileName      = 'BBASE.PIC';
  PowerFileName            = 'POWER.PIC';
  BoomFileName             = 'BOOM.PIC';
  SmokeFileName            = 'SMOKE.PIC';
  MineFileName             = 'MINE.PIC';

  Jeep                     = 1;
  Fire1                    = 2;
  Masheu                   = 3;
  Canon                    = 4;
  JeepCanon                = 5;
  _Power                   = 6;
  Score                    = 7;
  Fire2                    = 8;
  Boom                     = 9;
  _Mine                    = 10;
  BadCannon                = 11;
  BadFire                  = 12;

  Directions               = 72;
  OneAngSize               = 360 Div Directions;

